_, Protected_by_MoonSecV2, Discord = 'discord.gg/gQEH2uZxUk'


,nil,nil;(function() _msec=(function(e,n,o)local Z=n["دجؠآؠكؠ؃ق"];local G=o[e[(1275-0x28b)]][e["ضقددڪټكقضټزحڪ"]];local x=(49-0x2d)/(-72+(((0x26d-333)-0xcb)+-#'sp5rit suck'))local i=((0x26c-(797-0x1c9))/0x8c)-(-#{'}',",";33;'}',(function()return#{('oHhFfb'):find("\104")}>0 and 1 or 0 end);{};121}+8)local j=o[e[(0x102-138)]][e["قضسسآڪئڝڪض؃س؃ڪحننؠ"]];local C=(((349-((504+-0x6a)+-#[[Moonsec An IB2 fork sooo secure and we love it and federal is so straight and federal owns Luauth and we love spoons and if sonic was here federal would die a painful death and he would turn into dust]]))-0x7c)+-#[[You are an absolute baboon]])+(118-0x74)local A=o[e[(1198-0x273)]][e["جقسڝؠقټنټآدزقؠدزجكڪ"]]local d=(-#"get some bitches"+(-25+0x2b))-(0x35-(213-((0x112+-62)+-#[[how to find my dad at the dollar store getting milk]])))local t=(0x46-(-#[[mald]]+(((22-(53+-#{1;(function()return#{('lomBBL'):find("\109")}>0 and 1 or 0 end),(function()return{','}end)(),'nil',32;32;32}))+-#[[Obfuscated By Obamas Left Nut]])+0x7c)))local O=(-#{(function()return#{('lkHOFh'):find("\72")}>0 and 1 or 0 end),88,1;(function()return#{('lkHOFh'):find("\72")}>0 and 1 or 0 end)}+7)local _=(-0x67+((217+(-#"fix ownerof"+((-7500/0x7d)+-22)))+-#'free bobux no skem'))local s=(-#{{};(function()return#{('FBFHpp'):find("\70")}>0 and 1 or 0 end),(function()return#{('FBFHpp'):find("\70")}>0 and 1 or 0 end),44;'}',(function()return#{('FBFHpp'):find("\70")}>0 and 1 or 0 end)}+9)local b=(119-(-#{'nil';{},62,'}',34,34,34}+123))local u=(-#[[this is an ip grabber]]+(((-#'Alma Alma'+((0x79dd134a/(35+-#{(function()return{','}end)(),101;'}';'nil'}))/166))/178)/93))local B=(132-(133+-#{",";(function()return{','}end)();1,'nil','nil'}))local D=((144-(122+-#{111,{};'}';'}',1}))+-#[[Macaroni And The Cheese]])local P=(((0x2a03+(28+((-85-0x11)+-#"Alma Alma")))/0xb8)+-#'me when they are is have the me when are is do me when')local M=((((((59714553+-#{1;(function()return#{('pbBhmf'):find("\66")}>0 and 1 or 0 end),88})/105)/89)+-#"Impulse youtube real")/245)+-#"I watch gay furry porn")local p=(-#[[impulse was here omg]]+(0xa9-(0x13d-(0xea+(-0x36-8)))))local N=(-#[[impulse reel pastebin]]+(-0x5e+(((633-(0x321-422))+-0x7f)+-#[[Hey skid]])))local k=((41+-#{'}';75,'}',137,{},'nil'})-33)local U=(0x5b-((0x11b+((-40-0x1)+-#'turi ip ip ip'))-0x8c))local m=(0x118/(0x14a-(0x1ca-(-55+0x143))))local f=(0xfe/(((-0x55+4)+23449)/0xb8))local h=(22-(26+-#{(function()return{','}end)();'}';'}';1;(function()return#{('kKOPfm'):find("\79")}>0 and 1 or 0 end),(function()return{','}end)()}))local c=(0x54-((0x1e6-((0xb013+-93)/147))+-#"People trying to play roblox colon meanwhile crosswoods colon may I introduce myself question mark"))local Y=e[(-#[[ip grabbing in progress]]+(-0x68+1522))];local L=o[e[(0x4290/142)]][e["ض؃سقحححضكڝڝ؃ند"]];local I=o[(function(e)return type(e):sub(1,1)..'\101\116'end)('قن؃قئددد')..'\109\101'..('\116\97'or'حڪآئسدنڪ')..e[((1203-0x26f)+-#[[Ginglebog]])]];local w=o[e[(577+-#{24,24;(function()return{','}end)();1;",",24})]][e["كټسجزټؠن"]];local v=(22-0x14)-((-#"goofy ahh uncle productions"+(0x75-(0x8c+-56)))/3)local y=(-#[[monkey mode]]+(0x48-((0x5116-10433)/175)))-(0x19+-23)local F=o[e[(-#{{},44,{};'}';1,'nil'}+126)]][e["ڪس؃حقڝجڪؠآكڝكقق"]];local n=function(o,e)return o..e end local z=(0x79+-117)*(0x3c8/(-122+(84812/0xe9)))local W=o[e["زآڝكضدق؃حئقق؃ټ"]];local r=(-#"you get no absolute bitches"+(127-0x62))*(((((-#'bigchungus'+(-0x271a/70))+45)+-#'good googly moogly')+276)+-#[[I watch gay furry porn]])local H=(-#"Shrimps was here"+(0x175c0/92))*((((-24-0x25)+-#[[this code is skidded]])+439)/0xb3)local q=(-#[[Hey skid]]+(10620/(0x1dd-(0x152+-38))))local S=(53-(227-((0x96d2/195)+-#'windows xp startup sfx')))*(0x5e-92)local g=o[e["ڪټنق؃؃ئڝټجڝجزآس"]]or o[e[(1226-0x28f)]][e["ڪټنق؃؃ئڝټجڝجزآس"]];local a=(((2367-0x4ce)-596)-285)local e=o[e["ئڪح؃ټڝآحئدزئآئ"]];local A=(function(a)local r,n=2,0x10 local o={j={},v={}}local l=-d local e=n+i while true do o[a:sub(e,(function()e=r+e return e-i end)())]=(function()l=l+d return l end)()if l==(z-d)then l=""n=v break end end local l=#a while e<l+i do o.v[n]=a:sub(e,(function()e=r+e return e-i end)())n=n+d if n%x==v then n=y w(o.j,(F((o[o.v[y]]*z)+o[o.v[d]])))end end return A(o.j)end)("..:::MoonSec::..؃دحجئضسزقكنؠآټڪڝئنؠضندقټټئسنضدجټحكسحز؃ضؠجڪجڪ؃آن؃قكزضسدنڪنكقڪككددڪكټضآد؃؃ڝڪڝكآدآڝؠحنحقحزڝزحجضجححڝدټټقآزټڝؠنؠحكسح؃؃ڪڝضڪدآټآآئضټحسقڪټضسئضحټدك؃ضسدجڪجؠحكنحقڝزكسضضدكآز؃ئج؃ؠڪټټكآضڝز؃سڝؠټنؠئؠحنؠكؠزسسڝآؠڪ؃آدنټككآقټنټدؠحنڝقسزؠسآئټجنحټټككؠقدسټضكنقضقنكؠنسكحجنڝؠننضكدزټآن؃نئټحټدك؃ضجنئؠجڝحئ؃آڝحآآآنآجؠجقڪقزڪضڝكټكآضؠدؠئجكآآحجټڝسحڪسزؠ؃آزڪ؃نقآقڝن؃قضزدضټقآكڪكضزسزجئنجڝڪؠؠئكضقدسټكننككڪقسززئزئسجنحقدكڝسټقسڝضضئدحټكدزضضئجڪجضحدقضكجزكسضضدؠ؃آزؠكسؠكټئكزنؠؠكټقكزضنآؠسكآك؃سدسكئنئڪحسدڝڝئقآزدضټئكككقنق؃ضآضئئجحدضڪ؃ڪقدسټضكنآسزدسآدزجڪكقټجآح؃ټئقټحآڪزككجنؠجكزضحڝڝز؃ضد؃ڝؠزحآحجآ؃سآحدټزقسجدڪقضج؃ئؠحسجد؃آضز؃دټآټقئحؠڪحقټجڝڪككضئسڝننئضدڝڝڝضكسددآڝكحضسآآؠكئټڪقآؠزئ؃كآڪضټجئآ؃سكجآڪئند؃زؠټسنحټ؃قكآحنڝقآؠجقټټكققئ؃ضټآكج؃ڝآقسڪئدڪكزڪضقڝټكزسضدحنضحؠ؃حؠئجقحئؠئضآڝآڪضقق؃سڝآزؠضزڝقزدجزدئنسقسآزنككضقدټسآآؠدكئقكزقسقضسجڝدڪضنكجزټسكضضؠ؃ن؃ند؃قڝدټټآك؃د؃سڝئضټسؠضدجټحكڪدقئجضضڪقحدآحضكضزضسدئټزنقكزضئحسدئكجج؃ڪټآڪسڪئآضحڪجسحق؃ټڝكڪضجزحڝدق؃حټجؠئكؠحسجددټئكؠدسنڪحنحڪسڪآقجسكضضئدزڝزڪزحس؃ضدحڪؠقنزقټزكسضؠئكؠنئ؃نآآضڪ؃زآڝؠدكټقكآقټسؠڝكڝقسزئسحج؃ئنحنټؠكآقضزدضټقنقضسنجؠڝټڪضټدؠټڝدڝنڪحټد؃ڪئڪجددټ؃كسآئسحڝحددئ؃؃ڪقؠحككحححټدك؃ضڝدټټقك؃ؠڪدؠؠقحسضضدجټسؠقئسضسسدڝجئحج؃؃ڪڪنحسدئټجكحضددڝټڝددضزضنټككقضزدضټآكقؠسدكضددڪضټدؠټدكڝسڝئڪدؠڪنزكنقؠجزضقض؃جنڪقدزڝحڝئكقآنقآس؃ض؃ئؠضؠححنؠآدندقټزكؠكآجنسك؃زآسسضڝدڪجؠدس؃ؠڝټضزسڝئټجكحضضڝسحس؃ئكج؃دؠ؃آڝئټزټدكجققز؃ضؠحزڪؠټدؠټنكڝټټنؠزقدسسئ؃دڪددڝضڪدآټڝآ؃سڝټڪكآؠؠسنئكقآڪ؃ؠڝدټټآك؃حد؃ڝؠڪئآنآنجڪحټدض؃دڪټئ؃حسدڪ؃حڪسزؠسدئټجكدكآجئدټنجټآئټؠنحقضزدضټن؃كسقټزقسآضضجسحح؃ټدټقضسټضكئضزټقحسڝسك؃ڝټ؃ؠكنضكدآحؠآنضحججضدك؃ضڝدجڝجححكآڝڪڝڝدټئآجكقحڪدض؃دڪټحآحقح؃؃ڝڪڪحنسڝئټجكحضزقضڪضسجنجئدح؃زڝقټسقآؠدنككضزټڝنڪڪټدؠټنكڪحڪحټئآزنڪنضكحسټضنڪحټضؠكنضكدټ؃آڪآككئك؃ققززضسآدآڝؠضندقټڪجضدجڪآڪضټ؃ك؃حڝئټكآضؠدڝجڪڪټقټضؠآنؠضقڝج؃ئڪكټضآدڝ؃؃قڝزټسنئؠڪكڪزڪدضڝكڪضټدآڪحڝؠقئحټڝزؠڪڪكندڪ؃ټڝضڪدآټح؃؃سڝڪڪحسنسسئدحټدكضزضسئټجضدڪ؃ئڪڪڪټآنؠضك؃كټقئزجئڪئ؃حنؠحندقكزضسدنڝقضئڝجدڝڪڪڝټضآدنټ؃آڪټټحآدؠقنآ؃جدټڝكڪضټد؃؃آحئڪټئح؃ڪئكزدسنزجنټكسنڪڪقڪدسضآضڝسټضضئدحټضآسسسئئضنؠآئندقټزكنسؠضندسڪقؠسسضؠئټ؃ټدح؃ؠڪټڪدآسؠڝآدج؃ددڝټڪكحدحس؃ڪڝټڪنڪجؠڝؠقكسكجزدضئڪكټدؠټنكټټڪسآڪؠټزججضدټ؃كڝضحكجحدن؃كزضكحسكضضئدج؃آدضزټجسؠڝنزقآڪكجدڝزججزنټحټؠآجح؃دزحدآقضحزسنزضسدئټجكحضكدئؠحك؃ضآآنټككقضضؠ؃ضقؠدڝقټجدآؠضزټدسجڪټآجقؠسټضكئضزققحزټئقئسجڝحڝ؃ڪڝئڪحكزضټئدحټدكئڪضڝض؃جټدس؃ڝڝ؃ټڪآحضزجټحكدضزآضڝزؠجآآسندجڪزنسدئټجكزنضضسسضس؃زئكؠسككقضزدټئؠقنزقآق؃سكئسجئححضڪكسقدسټضكنئدجحس؃كڝضڪد؃ڝحق؃ك؃نآجټقآزنئكحڝؠ؃نڝدټټآكڝق؃ټڝآڝ؃ټجزڝئسحكدض؃دضئجنجحدسد؃ڪڪڪجټئؠحڪټحضددڝټڪكټضئدڝدټكڪ؃زضضټئكجضزدسڪسؠضكققآجنككضقدزڝ؃آكسدكننحڝض؃ڪنآټؠكنضڝئڪضآنآزنحك؃قټسنسجسضټسؠضندقټټنټضؠنسآن؃زنسجضضئقجئدآد؃ؠقڝټسسئټجكحضسجسسض؃جټجضټټكڝقضزدضټحقحڪكحڪټڝڝزؠڝڝآئنككضقدؠضآټؠكندسئسڪسككسټ؃ؠكنضكدڪؠآڪآآحجج؃دك؃ضڝدحئحڪحكڝڪكئزكسضضدججآټضسڪقزؠ؃زقڝكجندقكزضسدنڪنڪكحسآؠحڪټټضآدنټڪجڝقڪ؃آؠنئجآحد؃ټڝكئټئضجددكآڝؠ؃كآجټئآجددټ؃كڝؠقضح؃كڪحكؠڪضحح؃ضڝئدحټدك؃جقڝحڝنټجزټضضڪټټسك؃دسؠحټدض؃دڪټجنآؠسڝ؃دقنزڪسدئټجكزضزټضڪسحجنججڝئ؃ڪڪڪحسضڪئكجضحدزټضئڪټټدؠټنكټزڝ؃ټدټحقآننقڝزقڝسڪكآټؠكنضڪئڪ؃ټؠؠننڝزئقڪسڪڝئڪ؃آكؠضندك؃حټؠدټؠئزحكدض؃دڝققز؃ضكئحڝؠآئسآكضنټڝضجدآڝټڪكټضحټدحڝنڪكټسآڝؠآنكقحقدسآكنټكؠټنككضآكڪحآسنسكڝقآزحضكڪحټقؠكنضكدآكټقؠقنحككسكزدضحضسحڪحزڝآكززكسضضدقزكآقئسڝجدجڪحقح؃؃دڪڪڝڝززئټجكحض؃؃نڪجزآقئضآڝسآڪكزئؠآكڝدټؠئجئزقجدټڝسؠڝسسز؃ضقڝقسئضجددټ؃كڝضسددڝڝك؃حكټزټسكضضج؃ټؠسقټكق؃ڪكقټحزؠجحټؠڝئكنڪئجحكدض؃دحضټنكدكدجدحدزقسسئټجكحضح؃كڝحكآ؃ئآجضنڪقضزدضټكنز؃جق؃؃ؠټقضڝن؃سآڪئجدزټسندئڝضڝدڪڪسؠ؃زححسڝزقزكسزټسكضضقككآقزسنسنجقآڝؠضندقټآكټدؠحؠسقڪقزقكڝضټكآضؠدڪضڝټڪكټدكټنقكققضضقڝدټضآدنټټؠڝئټضټسك؃نڪكجزآضئڪڪټدؠټنكټقڪكآڪآؠنسكئكدسڪسز؃ڝټټؠكنضكدآضټڪآحنحكؠققسڪضضحڝجقحئدضټټټنټزآضكقحڝدض؃دڪټدنجحح؃دحڝزڪكؠآضدجكحضددزدضحئححسټؠنققضزدضټنټنققزحټسحضقڝدحض؃ن؃زڪڪټكؠڪؠقنئزق؃ڪڝضڪدآټڝڝدئ؃جڪ؃آڪضضئدحټدك؃ضڝدټټڝټڝضحككجزكسضضدكڝئټڪڪقضحضټنڝجؠنكټقكزضؠقؠآنؠك؃قئسټئنجقحس؃قنئقضزدضټنآكټقسز؃سئئقجححكدضڝنڝجئڝسحئضجددټق؃ضسئټجقحآدضڝسڪحآټټآئدحټدك؃ضڝدټټ؃ئڝضقجكحزكسضضدق؃كدزنزئسدضقآضؠدكټقؠنسسدئټجكحكددڝټڪكڪزڪڝنټككقضټ؃ضټئكجضحد؃ټڝكڪضټدؠټنككضقدسټضكئضجحدټ؃كڝضڪدآټآؠنضكدزڪسكسدئدحټدكدزڝدټټآنؠضڪټقټزكسضززجټحكدس؃دڝسټكآسؠدڪدقكزكقزئټجكحضدنڝټڪنټضآضټجككقضزدسزئكجسحد؃ټ؃حڪضټدؠټننكضقدسټضؠزسجددڪ؃كڝضڪدآټؠكؠزكئزټسنضضزنحټدك؃ضڝدج؃آكؠسندقټزكسضضدئڝضقدض؃جڪټئئآضؠدكټقؠنسسدض؃جكحسددڝټڪكټضټكنټكټقضزحضټئكجضحد؃ټڝكڪنټدآ؃نككضقدزڝضكئضجزدټسڝڝضڪدآټؠكنضكدقحسكضزئدحڝدك؃ؠڝدټټآټؠضڝڪقټزنسضضسجټحټجؠ؃دڪټټكححؠدكڪقكزضؠحئټجڪحضدئڝټڪكټضټجآټككقؠزدسدئكجضحددڝڝكڪضټقؠټڪحكضقدسټسؠئضجدحض؃كزدڪدآټؠكؠزكدزټزحضضقنحټدك؃ض؃جټټآكؠڝندڝكزكسضضدجټحكدض؃قڪټڪجآضؠجكټقكزضسدضججكحؠدد؃ئڪكټضآدنټكڪقضزجضټئؠجضحز؃ټڝكڪكټددننككسقدزحضكئكضزدټ؃كڝضجڪآټؠننضكدآڪسكضنئدج؃دك؃ضڝدڪڝڪكؠضنزقټزټسضضدجټجؠدض؃دڝئټكڝڪؠدكټقكقزسدئټئدحضجنڝټڪكټضټجنټككقڪزدزنئكجضحددڝڝكڪضټؠؠټحئكضقدسټضكئضجدحئ؃كڝڝڪدآڝؠكنضكدزټسڝضضئزحټح؃؃ضڝدټټآكؠنندقڝزكسزضدئجحكدض؃ضڪټجسآضؠحكټقڪزضسضزججكحضددضنڪكټسآدنټڪنقضزسضټئآجضحد؃ټڝؠدسټدآجنككزقدسټضكئضق؃دټ؃ڪڝضڪجآټؠؠنضكزقكسكضنئدقكدك؃سڝدټټآكؠكآزقټزكسضنټجټحندض؃دجڪټكآنؠدن؃قكزضسدضڝسڪحضدزڝټجؠټضآدنټنؠقضزدسئئككنحد؃ټڝكڝزټدؠټؠدكضڪجسټضكئضجددټ؃كڝآڪدټئؠكنټكدقجسكضضئقحټضد؃ضڝحټټآكؠضنضؠجزكسضضدزضحكدس؃دڝدڝڝآضؠدكټآسزضسحئټئؠسضدد؃ئڪك؃ڪآدنټكككزن؃ضټضدجضقد؃ټڝكڪضڪجڪآنككڪقدټؠضكئضجدحڝجقڝضڪؠآټټڪنضكدزټسكزټئدجئدك؃ڝڝدټڝآكؠضنققټزڝسضضزجټج؃دض؃زڝكټكآؠؠدټڪقكزسسدئټجكحكجزڝټڪكټض؃حنټكنقضزضقجئكجضحدئڝڝكڪسټدآڝڪككضقزسټؠزئضجددټ؃كئئڪدټحؠكنزكدزڝسكضؠسضحټدټ؃ضئڪټټآنؠضنسقټزټقؠضدجټحكزح؃دڪڪټكآض؃حكټقڪزضسئئټجكحضحجدټڪكټؠآدڝڝككقضزدسڝئكجضحق؃ټجحڪضټدؠټؠؠكضقدزضضكقدجددټ؃ك؃زڪدآټآحنضندزټسكضضضجحټدك؃ڝڝدضټآكؠضندقټزكسضضقجټججدض؃جڪټټكآضؠدنجقكزؠسدضئجكحضددڝټڪڪټضآجنټكؠقضززضټئكجكحدسنڝكڪسټدآحنكككنزسټضكئضقڪدټ؃نڝضڪددڪؠكننكدق؃سكضضئدجڝجز؃ضڝزټټدؠؠضندقټقؠسضضدئئحكئڪ؃دڪټټكټزؠدكټكدزضؠآئټجكحضحجڝټڪكټڪآدڪجككقضزدسڝئكجضحؠ؃ټدټڪضټدؠټنككضقدزئضكئڝجددڝ؃كڝضڪدآټؠڝنضكززټز؃ضضئدحټدك؃نڝدټڝآكؠزندقټزكسضضضجټحڪدض؃دڪټټټآضؠدكټقكټحسدئڪجكحضحئڝټڪټټضآدنټككقضزدؠ؃ئكجكحد؃ڪڝكڪضټدآجؠضكضقضسټآ؃ئضجحدټ؃كڝضڪضڝجؠكنضكدڪئسكضسئدضټحن؃ضڝسټټڪټؠضؠنقټقؠسقضدئححكدڝ؃دڪټټكآضؠنكټقكزضسحئټجكحضحججټڪكټنآددآككقضزدسجزسجضحز؃ټڝآڪضټحؠټننكضقدكقضكئضجددڝ؃كڝضڪدآټآزنضكسزټسؠضضئححټدټحؠڝدټټآكدزندقڪزكززكدجټحڪدض؃زڪټټكآضڪدڪ؃قكزنسدزنجكئ؃دد؃ڝڪكټضآسنټكڝقضزدضټضؠجضحددجڝكدڪټدؠټنكنزقدسټس؃ئضئئدټ؃كڝضڝجآټؠكنټكدټجسكضضئدجڝدك؃ضڝنټټ؃ڪؠضندقټزكسضضدئجحكدڪ؃دڪڝټكټضؠدكټقڪزضؠؠئټجڝحضحجڝټڪكټنآدؠجككقضزدسڝئكجضحز؃ټجحڪضټدؠټؠؠآئقدزئضكؠضجددټ؃ك؃زڝټآټآدنضنقزټسكضضضجحټدك؃ڪڝدحټآكؠضندقټزكسضضزجټجحدض؃جڪټڪكآضؠدنحقكؠؠسدضججكجزددڝټڪڪټضآزنټككقضقجضټئكجؠحدئسڝكڪضټدآڝنككضققسټكزئضجددټدؠڝضڪدټضؠكنڪكدزټسكسزئدحټحح؃ضدجټټآكؠضندقټزكسؠضدئسحكدز؃دڝټ؃آآضؠسكټڝسزضسزئټجكحڪددڝټڪكټسآدنټككقضزسضټئكجضحك؃ټڝكڪضڝڪؠټنككضقدسټضكؠضزدنز؃ټڝضڪدآټؠنضټڪئسدسنضضئدحټدكسحڝټټټآكؠضؠقجټټ؃حزڪجسسڪنزڝد؃قح؃ڪك؃ؠئندقكزضسدئڝڪ؃سض؃حؠئڪآټضآدنټنؠجكؠحجڪئكجضحد؃ټڝكڪضآدڝآ؃سكؠقدسټضكضزڪئسڪڝدقح؃زڪڪؠكنضكدقڝنكضضئئحټدټ؃ضڝدټټآكؠآندك؃زكسقضدجڪحكدؠ؃ټڪټټآآضؠقكټقنزضسدئټجټئؠددڝټڪكټآآدنڪكككزؠدضټئآجضحض؃ټڝكڪضټدآئنككققدز؃ضكئسجددټجكڝضڪئآټؠؠنضكدزټزؠقئئدج؃دك؃آڝدټټآكآزنؠقټزټسضضئجټحكدضدجڪټټكآنؠدنئقكزضسدئټجكحضدزڝټڪكټضآدنټنؠقضزدسئئكجآحد؃ټڝكڪكټدؠټنڪكضكڪسټضنئضجدسڪ؃كڝڪڪدټدؠكنضكدقڝزئضضئؠحټحد؃ضڝدټټڪكؠضندكززكسڝضدئححكجض؃دڪټڪئآضؠدكټقڝزضسدئټجكجحدد؃ضڪكټضآدنټككقضزڝضټضدجضحد؃ټڝكڪضټدآقنكنجقدسڝضكسضجددټدئڝضڪآآټؠؠنضكدزټسكس؃ئدحڝدك؃زڝدټټآكؠضنآقټقئسضضئجټئكدض؃دڝقټكټ؃ؠدكڪقكزضسدئټئجحضدجڝټڪؠټضآدنټككقكزدسسئكجڝحد؃ټڝكڪضټنؠټنآكضقجسټزكئضجدح؃؃كڝڪڪدآڪؠكنكنززټسڪضضئڪحټدن؃ض؃جدټآكؠنندكدزكسضضدجټجټدض؃سڪټټنآضؠضكټقكنضسدضدجكحزددڝټڪكټضآننټككقضزحضټئكجضحئ؃ټڝكڪضټدؠڪنككضقدحئضڪئضجددټدقكزحدؠقئئنټكدزټسكضضكئحټدن؃ضڝدټټآكؠضؠجآټزكسزضدجڪحكدض؃دڝج؃سآضؠئكټقكزضسحئټجؠحضددحقڪكټضآدنڪككقضزدضټزئجضحد؃ټڝكڪضټدؠټنكنجقدسڝضكئزجددڪ؃كڝضددآټؠننضكجزټسكضضئدجسدك؃ضڝدټڪآكؠضندقڪزنسضضدجټحټدض؃دڪټسجآنؠدكټقكزق؃ضقڪحټنؠدئ؃زڪكټضآدؠضئؠټ؃ضجڪقزز؃زكضدڪكټسڝټټؠټنككضقكدڝكزج؃نڝجڝټئسجڝجقد؃نقكزضقكسكضضئدججؠټضقټجسؠڝسقزدئقټحسؠقئجئټحكدض؃دڝڝدكآضؠدكټقؠزضسدئټجڝضدددڝټڪكڪدآدنڪككقسزدسدسڝجضحد؃ټ؃ضڪضټحؠټؠؠټضقدسټضكئقجددټ؃كڝؠ؃ټآټؠكنضكټزټسنضضئححټدټحؠڝدټټآكآدندقڪزكززكدجټحكدض؃ضڪټټكآضؠزنكقكزضسدضزجكحسددڝټڪكټكڪزنټككقضزؠضټئنجضحضججڝكڪضټدآكنككسقدزڝككئضجددټ؃نڝضڪدآټټكآقكدزټسكضضئدجددك؃ضحزټټآنؠضنحقټزكسضضدقآحكدض؃دڪڝټكآزؠدكټآټزضسدئټجكحضددڝټڪكټڪآدنټككقسزدضټئكجضحد؃ټڝكڪضټدؠټنككضقحسټضكئضجدحس؃كڝضڪدآڪؠكنضكدزټسكضضئدحټدن؃ضڝدټټحسؠنندقټزكزئ؃حقضدسنق؃ضڪټټكآضآجټټقكزضسدئڪجكحضددڝټدڝټضآحنټككقضزدضټئكئجحد؃ټڝكڪزټدؠڪنككضقنسټضكئضجحدټ؃كڝضڪدآټؠكنضكدزڝسكضضئدقزدك؃ضڝدټټآكؠضندقټټسسنضدجټحكحئنجحټآئض؃آآكټقكزضزجزآجكحزددڝڪڪكټضآدؠڝآققضزئضټئنجضحد؃ټ؃ؠحضټدآدنككزقدسټضكئؠضڪدټ؃ڪڝضڪدآټؠننضكضزټسكق؃ئدحټدك؃زڝدټټآكؠضآآقټزكسضضدجټحكدض؃ددقټكآضؠدن؃قكزضسدئټسئحضددڝټڪنټضآدنټكككجزدسدئكجزحد؃ڪڝكڪؠدڪؠټنككضكقسټضنئضجحدټ؃ټدؠڪدآټؠكؠآكدزڪسكضؠقڪحټدك؃ض؃قټټآنؠضنحقټزټقؠضدجټحكحآ؃دڪڪټكآؠڝڪكټقنزضزقئټجنحضددڝټڪټڝؠآدنټكككآزدضڪئكجضس؃؃ټڝټڪضټجؠټنآكضقدنآضكئنجدح؃؃كڝزڪدټج؃سنضكضزټق؃ضضئححټدڪ؃ضڝض؃جآكؠضندنئزكسسضدجټسقدض؃ضڪټټؠآضؠئكټقكؠئسدضحجكحقددڝڝڪكټؠ؃آنټكټقضقكضټئنجضحس؃ټڝټ؃ؠټدؠټنكنټقدسڪضكئضئئدټ؃ټڝضڪدآټؠكنضكدټ؃سكضكئدحڪدك؃ضڝدټټڝكؠضنضقټزؠسضضدجټحكدڪ؃دڪټټكآسؠدكټقكززسحئټجكحضددڝټڪكټضآقنټككقضزدكڪئكجضحد؃ڪڝكڪضټدؠټنككضقدسټضكئضجددټ؃كڝضڪدآټؠكنضكدزټسكضضئدحټدك؃ضڝئټټآكؠضندقټزكسضضدجټحكدض؃دڪټټكآضؠدكټقؠزضسدئټجكحضددڝټڪكټسآدنټككقضزدضټئكجض");local w=((-#[[aint you nathaniel b]]+(112880/0x53))/67)local l=55 local o=d;local e={}e={[(-#[[get funnier L]]+(-105+0x77))]=function()local n,e,d,i=j(A,o,o+C);o=o+S;l=(l+(w*S))%a;return(((i+l-(w)+r*(S*x))%r)*((x*H)^x))+(((d+l-(w*x)+r*(x^C))%a)*(r*a))+(((e+l-(w*C)+H)%a)*r)+((n+l-(w*S)+H)%a);end,[(-35+0x25)]=function(e,e,e)local e=j(A,o,o);o=o+i;l=(l+(w))%a;return((e+l-(w)+H)%r);end,[((-122+0x85)+-#"Hey skid")]=function()local e,n=j(A,o,o+x);l=(l+(w*x))%a;o=o+x;return(((n+l-(w)+r*(x*S))%r)*a)+((e+l-(w*x)+a*(x^C))%r);end,[(644/0xa1)]=function(o,e,n)if n then local e=(o/x^(e-d))%x^((n-i)-(e-d)+i);return e-e%d;else local e=x^(e-i);return(o%(e+e)>=e)and d or y;end;end,[(-#"moon sex is better than lua guard"+(0xc2c/82))]=function()local o=e[(0x1f-30)]();local l=e[(90-0x59)]();local c=d;local n=(e[((3042/0xea)+-#"ambatakum")](l,i,z+S)*(x^(z*x)))+o;local o=e[(78+-0x4a)](l,21,31);local e=((-d)^e[(-#[[Pipe te amo]]+((1738-0x3a0)/54))](l,32));if(o==y)then if(n==v)then return e*y;else o=i;c=v;end;elseif(o==(r*(x^C))-i)then return(n==y)and(e*(i/v))or(e*(y/v));end;return G(e,o-((a*(S))-d))*(c+(n/(x^q)));end,[(87+-0x51)]=function(n,x,x)local x;if(not n)then n=e[(110-(-#"moonsex looks great"+(0x16e-238)))]();if(n==y)then return'';end;end;x=L(A,o,o+n-d);o=o+n;local e=''for o=i,#x do e=Y(e,F((j(L(x,o,o))+l)%a))l=(l+w)%r end return e;end}local function H(...)return{...},W('#',...)end local function A()local c={};local b={};local o={};local u={c,b,nil,o};local n={}local w=(-118+0xd6)local l={[((0x160-233)-117)]=(function(o)return not(#o==e[((-53+0x50)-25)]())end),[(-17+0x11)]=(function(o)return e[((51+-0x10)+-#"testing this thingy lololollez")]()end),[(90-0x59)]=(function(o)return e[(1032/0xac)]()end),[(147/0x31)]=(function(o)local n=e[(-22+0x1c)]()local o=''local e=1 for l=1,#n do e=(e+w)%a o=Y(o,F((j(n:sub(l,l))+e)%r))end return o end)};local o=e[(0x2b-42)]()for o=1,o do local e=e[(-#"how tf do i remove the meme strings"+(0xa5-128))]();local d;local e=l[e%(0xbf-146)];n[o]=e and e({});end;for b=1,e[(24-0x17)]()do local o=e[(0x6a+-104)]();if(e[(712/(458-0x118))](o,d,i)==v)then local r=e[(-#"Quiero pene"+(0x3a+-43))](o,x,C);local l=e[(122-0x76)](o,S,x+S);local o={e[(0x51-78)](),e[(-#[[bring MoonSec v3 back]]+(108+-0x54))](),nil,nil};local a={[((0x7a-109)+-#"nerd emoji x7")]=function()o[O]=e[(0x162/118)]();o[M]=e[(-#[[sex in fortnite real]]+(0x159/15))]();end,[(0x5a-89)]=function()o[_]=e[(-#[[send nudes]]+(2739/0xf9))]();end,[((0x52-66)+-#'sexo 4 o filme')]=function()o[t]=e[(-#"Only a to Z 0 to 9 is allowed"+(4620/0x9a))]()-(x^z)end,[(((17424/0x16)/0x18)+-#'imagine not being able to talk')]=function()o[_]=e[((0x8a-117)+-#'go kys go kys go kys')]()-(x^z)o[D]=e[((0x248/8)-70)]();end};a[r]();if(e[((6633/0xc9)+-#'Only A to Z 0 to 9 is allowed')](l,i,d)==i)then o[h]=n[o[f]]end if(e[(-0x67+107)](l,x,x)==d)then o[O]=n[o[t]]end if(e[(0x1c/7)](l,C,C)==i)then o[p]=n[o[N]]end c[b]=o;end end;u[3]=e[(103+(-#[[flat]]+(-0x3f47/167)))]();for e=i,e[((((0x770-990)+-#'You are an absolute baboon')/0x6f)+-#[[mama mo]])]()do b[e-i]=A();end;return u;end;local function y(e,S,w)local o=e[x];local r=e[C];local e=e[d];return(function(...)local A={};local v=o;local o=H local a=e;local C={};local e=d e*=-1 local e=e;local l={};local r=r;local j=W('#',...)-i;local z={...};local o=d;for e=0,j do if(e>=r)then A[e-r]=z[e+i];else l[e]=z[e+d];end;end;local e=j-r+d local e;local r;while true do e=a[o];r=e[(0x4/4)];n=(1257100)while(0x8dc/54)>=r do n-= n n=(309096)while r<=(0x7d-105)do n-= n n=(7049326)while r<=(-#[[go kys go kys go kys]]+(0x5e+-65))do n-= n n=(270125)while(0x3e-58)>=r do n-= n n=(6965100)while r<=(0x3e-61)do n-= n n=(6759898)while(0/0x55)<r do n-= n l[e[m]]=(e[b]~=0);o=o+i;break end while(n)/((8205-0x1016))==1654 do l[e[U]][e[s]]=e[N];break end;break;end while 2180==(n)/((3263+-0x44))do n=(3864224)while((-#[[good googly moogly]]+(871-0x1c3))/0xc9)>=r do n-= n l[e[c]][e[O]]=e[B];break;end while(n)/((5337-(0x59158/136)))==1456 do n=(6255340)while(0x28e/218)<r do n-= n l[e[m]]=l[e[u]][e[D]];break end while 2548==(n)/((0x7579c/196))do w[e[u]]=l[e[h]];break end;break;end break;end break;end while 125==(n)/((0x76b51/225))do n=(3917184)while((((363-0xda)+-#"hamburger")-81)+-#[[Uh summa lumma dooma lumma you assumin Im a human]])>=r do n-= n n=(5680080)while r>(1205/0xf1)do n-= n l[e[U]]=e[u];break end while(n)/((0x746+-98))==3220 do l[e[c]]=S[e[u]];break end;break;end while 2424==(n)/((0x64360/254))do n=(1161191)while r<=(83-0x4c)do n-= n l[e[k]]=l[e[u]][l[e[M]]];break;end while(n)/((0xf5e-2021))==607 do n=(10515216)while(1944/0xf3)<r do n-= n do return end;break end while(n)/((0xbb020/202))==2773 do local n=e[h];local o=l[e[b]];l[n+1]=o;l[n]=o[e[p]];break end;break;end break;end break;end break;end while(n)/((8134-0x1013))==1754 do n=(187187)while(108-0x5e)>=r do n-= n n=(2781729)while r<=(-122+0x85)do n-= n n=(5916984)while(0x78/12)<r do n-= n local S;local r;local c;local n;l[e[f]]=w[e[t]];o=o+d;e=a[o];l[e[m]]=l[e[t]][e[M]];o=o+d;e=a[o];n=e[m];c=l[e[O]];l[n+1]=c;l[n]=c[e[B]];o=o+d;e=a[o];l[e[f]]=l[e[b]];o=o+d;e=a[o];l[e[f]]=l[e[b]];o=o+d;e=a[o];n=e[m]l[n]=l[n](g(l,n+d,e[t]))o=o+d;e=a[o];n=e[k];c=l[e[s]];l[n+1]=c;l[n]=c[e[B]];o=o+d;e=a[o];n=e[h]l[n]=l[n](l[n+i])o=o+d;e=a[o];r={l,e};r[i][r[x][U]]=r[d][r[x][p]]+r[i][r[x][s]];o=o+d;e=a[o];l[e[h]]=l[e[s]]%e[D];o=o+d;e=a[o];n=e[f]l[n]=l[n](l[n+i])o=o+d;e=a[o];c=e[_];S=l[c]for e=c+1,e[D]do S=S..l[e];end;l[e[m]]=S;o=o+d;e=a[o];r={l,e};r[i][r[x][f]]=r[d][r[x][p]]+r[i][r[x][u]];o=o+d;e=a[o];l[e[h]]=l[e[O]]%e[D];break end while(n)/((0x9c4+-76))==2441 do local i;local r;local n;l[e[k]]=e[s];o=o+d;e=a[o];l[e[f]]=e[O];o=o+d;e=a[o];l[e[c]]=#l[e[b]];o=o+d;e=a[o];l[e[c]]=e[u];o=o+d;e=a[o];n=e[c];r=l[n]i=l[n+2];if(i>0)then if(r>l[n+1])then o=e[O];else l[n+3]=r;end elseif(r<l[n+1])then o=e[O];else l[n+3]=r;end break end;break;end while 807==(n)/((0x66ab6/122))do n=(997668)while(89-0x4d)>=r do n-= n if l[e[h]]then o=o+d;else o=e[b];end;break;end while 1926==(n)/(((-#'this is an ip grabber'+(0x39b5c/212))-576))do n=(5387454)while r>(-0x7f+140)do n-= n local e=e[f]l[e](l[e+i])break end while(n)/(((4031+-0x61)+-#'tunnelposting'))==1374 do local r;local n;l[e[c]]=w[e[s]];o=o+d;e=a[o];l[e[h]]=w[e[O]];o=o+d;e=a[o];l[e[c]]=e[u];o=o+d;e=a[o];l[e[c]]=e[b];o=o+d;e=a[o];l[e[c]]=e[b];o=o+d;e=a[o];n=e[k]l[n]=l[n](g(l,n+d,e[_]))o=o+d;e=a[o];l[e[U]]=l[e[O]][l[e[M]]];o=o+d;e=a[o];n=e[k]l[n]=l[n](l[n+i])o=o+d;e=a[o];r=l[e[P]];if not r then o=o+i;else l[e[h]]=r;o=e[s];end;break end;break;end break;end break;end while(n)/(((30380/0x7c)+-#'0nly 1337 smashed ur wap'))==847 do n=(2229550)while r<=(1649/0x61)do n-= n n=(7674395)while r<=(0x258/40)do n-= n local e=e[k]l[e]=l[e](l[e+i])break;end while(n)/(((0x22398/72)+-#'You are an absolute baboon'))==3995 do n=(138067)while(-#"gay men"+(98-0x4b))<r do n-= n local e={l,e};e[d][e[x][k]]=e[x][B]+e[x][t];break end while 1367==(n)/((168+(-0x43+0)))do local n=e[c];local d=l[n]local a=l[n+2];if(a>0)then if(d>l[n+1])then o=e[s];else l[n+3]=d;end elseif(d<l[n+1])then o=e[_];else l[n+3]=d;end break end;break;end break;end while 3050==(n)/((0x5d5-762))do n=(593791)while r<=(-#[[moon sex is better than lua guard]]+(182-0x83))do n-= n l[e[k]]=l[e[O]][l[e[M]]];break;end while 253==(n)/((0x8cf52/246))do n=(7468952)while(-#"algebra"+(0x94+-122))<r do n-= n l[e[k]][l[e[s]]]=l[e[M]];break end while 2503==(n)/((-#[[How to give a motherfuckin audience a feeling like its levitating]]+(0x180a-3105)))do l[e[h]]=(e[_]~=0);o=o+i;break end;break;end break;end break;end break;end break;end while(n)/((0xd5+-105))==2862 do n=(8668828)while r<=(0xffc/132)do n-= n n=(4520480)while r<=((14770/0xd3)+-#"Smokey BArbecue BAcon BUford from checkers mm")do n-= n n=(1295030)while r<=(0x95e/109)do n-= n n=(3008716)while r>(57+-0x24)do n-= n local n=e[h];local a=l[n+2];local d=l[n]+a;l[n]=d;if(a>0)then if(d<=l[n+1])then o=e[_];l[n+3]=d;end elseif(d>=l[n+1])then o=e[t];l[n+3]=d;end break end while 3373==(n)/(((0x20978/148)+-#'While true'))do if(l[e[c]]~=l[e[D]])then o=o+i;else o=e[u];end;break end;break;end while 671==(n)/((0x7a1+-23))do n=(3127800)while(-#[[Fucking losed 027728272728271]]+(-45+0x61))>=r do n-= n local n=e[s];local o=l[n]for e=n+1,e[M]do o=o..l[e];end;l[e[h]]=o;break;end while(n)/(((0x398+-89)+-#'Only a to Z 0 to 9 is allowed'))==3900 do n=(5753994)while r>(-0x72+138)do n-= n l[e[h]]={};break end while 3202==(n)/((1923+-0x7e))do local r;local n;l[e[c]]=(e[b]~=0);o=o+d;e=a[o];l[e[U]]=l[e[b]];o=o+d;e=a[o];l[e[k]]=w[e[b]];o=o+d;e=a[o];n=e[h]l[n]=l[n](l[n+i])o=o+d;e=a[o];r=l[e[N]];if not r then o=o+i;else l[e[U]]=r;o=e[t];end;break end;break;end break;end break;end while(n)/((0x24aab/101))==3040 do n=(5257604)while(-0x4d+105)>=r do n-= n n=(749666)while r<=(115+-0x59)do n-= n local n=e[c];local a=l[n+2];local d=l[n]+a;l[n]=d;if(a>0)then if(d<=l[n+1])then o=e[u];l[n+3]=d;end elseif(d>=l[n+1])then o=e[s];l[n+3]=d;end break;end while(n)/(((2773-0x58c)+-#[[You say is ricochetin off of me and itll glue to you and]]))==578 do n=(14582928)while((0x193b-3246)/119)<r do n-= n local n;l[e[U]]=e[b];o=o+d;e=a[o];l[e[c]]=e[_];o=o+d;e=a[o];n=e[m]l[n]=l[n](g(l,n+d,e[t]))o=o+d;e=a[o];l[e[h]][e[t]]=l[e[N]];o=o+d;e=a[o];l[e[f]]=w[e[_]];o=o+d;e=a[o];l[e[k]]=w[e[u]];o=o+d;e=a[o];l[e[c]]=e[O];o=o+d;e=a[o];l[e[f]]=e[s];o=o+d;e=a[o];l[e[c]]=e[b];o=o+d;e=a[o];n=e[h]l[n]=l[n](g(l,n+d,e[t]))break end while(n)/((0x2fca0/48))==3576 do S[e[s]]=l[e[U]];break end;break;end break;end while(n)/(((-0x6d+1600)+-#[[funtime foxy and funtime freddy having sex real]]))==3641 do n=(4676650)while r<=(-#[[Ur mom]]+(168-0x85))do n-= n if(l[e[k]]==l[e[p]])then o=o+i;else o=e[u];end;break;end while(n)/((0xc4b-(339412/0xd4)))==3025 do n=(7893990)while(-0x39+87)<r do n-= n l[e[c]]=l[e[_]]%e[M];break end while(n)/((0x148c-2665))==3042 do local n;l[e[m]]=w[e[s]];o=o+d;e=a[o];l[e[k]]=w[e[_]];o=o+d;e=a[o];l[e[c]]=e[O];o=o+d;e=a[o];l[e[h]]=e[O];o=o+d;e=a[o];l[e[m]]=e[_];o=o+d;e=a[o];n=e[U]l[n]=l[n](g(l,n+d,e[b]))o=o+d;e=a[o];l[e[f]]=l[e[u]][l[e[P]]];o=o+d;e=a[o];n=e[U]l[n]=l[n](l[n+i])o=o+d;e=a[o];l[e[c]]=l[e[t]];o=o+d;e=a[o];o=e[_];break end;break;end break;end break;end break;end while(n)/((-#'Moonsex v5 eta'+(534240/0xf0)))==3919 do n=(67960)while r<=(3564/0x63)do n-= n n=(2710250)while(0x64-67)>=r do n-= n n=(1270016)while r>(138+-0x6a)do n-= n local e={l,e};e[i][e[x][h]]=e[d][e[x][N]]+e[i][e[x][_]];break end while(n)/(((66285-0x81ad)/47))==1804 do local r;local n;l[e[m]]=w[e[t]];o=o+d;e=a[o];l[e[h]]=w[e[b]];o=o+d;e=a[o];l[e[f]]=e[b];o=o+d;e=a[o];l[e[m]]=e[s];o=o+d;e=a[o];l[e[h]]=e[b];o=o+d;e=a[o];n=e[f]l[n]=l[n](g(l,n+d,e[b]))o=o+d;e=a[o];l[e[c]]=l[e[u]][l[e[B]]];o=o+d;e=a[o];n=e[c]l[n]=l[n](l[n+i])o=o+d;e=a[o];r=l[e[D]];if not r then o=o+i;else l[e[h]]=r;o=e[t];end;break end;break;end while(n)/(((0x1f140/136)+-#[[panzerfaust]]))==2930 do n=(12302883)while(0xac-138)>=r do n-= n l[e[h]]=#l[e[O]];break;end while 3789==(n)/((6578-0xd03))do n=(9424233)while(0x1810/176)<r do n-= n local n=l[e[B]];if not n then o=o+i;else l[e[m]]=n;o=e[s];end;break end while(n)/(((0x54849/147)+-#"big niggers sucking cock"))==4043 do l[e[U]]=l[e[t]][e[B]];break end;break;end break;end break;end while 40==(n)/((84950/0x32))do n=(11594030)while(-0x24+75)>=r do n-= n n=(10810371)while r<=(0xaf-138)do n-= n local e=e[U]l[e](l[e+i])break;end while 3729==(n)/(((3027+-0x55)+-#[[Im devastating more than ever demonstrating]]))do n=(6578429)while(2432/0x40)<r do n-= n local e={l,e};e[i][e[x][c]]=e[d][e[x][B]]+e[i][e[x][u]];break end while 3341==(n)/((-120+0x829))do o=e[s];break end;break;end break;end while 3722==(n)/((127715/0x29))do n=(4116175)while(0x23a0/228)>=r do n-= n local o=e[c]l[o]=l[o](g(l,o+d,e[O]))break;end while 1505==(n)/(((0xa3c24/244)+-#'0 divided by 0'))do n=(2891770)while((0xde+-89)+-92)<r do n-= n do return end;break end while 1895==(n)/(((287045/0xbb)+-#'Alma Alma'))do local n=l[e[P]];if not n then o=o+i;else l[e[U]]=n;o=e[b];end;break end;break;end break;end break;end break;end break;end break;end while(n)/((116350/0xb3))==1934 do n=(5094408)while(-#"Your cookie has been leaked"+(0xeb-145))>=r do n-= n n=(4166942)while r<=((0xb0-113)+-#"panzerfaust")do n-= n n=(9228541)while r<=(-115+0xa2)do n-= n n=(12538195)while(-#[[MSC 793z487nhvcgsdfgsudfza9889jgvz56gz56z547684z5g54z948g56z74j56475jzg645z6456 oh wait bitch]]+(-0x18+161))>=r do n-= n n=(1197800)while(-97+0x8c)<r do n-= n if not l[e[U]]then o=o+i;else o=e[s];end;break end while 565==(n)/((4289-(0x4913a/138)))do l[e[k]]=l[e[t]];break end;break;end while 3629==(n)/((0x5381d/99))do n=(7452538)while(-#"mald"+(120-0x47))>=r do n-= n local r=v[e[_]];local d;local n={};d=I({},{__index=function(o,e)local e=n[e];return e[1][e[2]];end,__newindex=function(l,e,o)local e=n[e]e[1][e[2]]=o;end;});for d=1,e[B]do o=o+i;local e=a[o];if e[(-39+0x28)]==43 then n[d-1]={l,e[s]};else n[d-1]={S,e[t]};end;C[#C+1]=n;end;l[e[k]]=y(r,d,w);break;end while(n)/((0x1c91-3711))==2069 do n=(1164178)while(-#[[You are an absolute baboon]]+(140+-0x44))<r do n-= n l[e[k]]=e[b];break end while 821==(n)/((0xb28-1438))do w[e[_]]=l[e[U]];o=o+d;e=a[o];l[e[f]]={};o=o+d;e=a[o];l[e[f]]={};o=o+d;e=a[o];w[e[u]]=l[e[c]];o=o+d;e=a[o];l[e[U]]=w[e[u]];o=o+d;e=a[o];if(l[e[U]]==e[P])then o=o+i;else o=e[t];end;break end;break;end break;end break;end while 2621==(n)/((((0x856b8-273292)/0x4d)+-#'yeah u know what time it is'))do n=(184338)while((-103+0xcf)+-#[[Wenomechainsama Tumajarbisaun Wifenlooof Eselifterbraun]])>=r do n-= n n=(157779)while r>(0xbf-143)do n-= n l[e[f]]=y(v[e[t]],nil,w);break end while 141==(n)/((-125+0x4dc))do do return l[e[m]]end break end;break;end while(n)/((2800-0x586))==133 do n=(715300)while r<=(0x2710/200)do n-= n local o=e[c]l[o]=l[o](g(l,o+d,e[u]))break;end while(n)/(((0x421-577)+-#'aint you nathaniel b'))==1555 do n=(2334458)while((-#"qwertyui is hot"+(-0x7d+358))-0xa7)<r do n-= n local n=e[O];local o=l[n]for e=n+1,e[M]do o=o..l[e];end;l[e[c]]=o;break end while 686==(n)/(((0x6c8b8/130)+-#"beliveri12 is gay"))do l[e[U]][e[_]]=l[e[D]];break end;break;end break;end break;end break;end while(n)/((0x160ee/50))==2306 do n=(1854608)while(0xb0-119)>=r do n-= n n=(8499324)while(-0x49+127)>=r do n-= n n=(1605975)while(0x67+-50)<r do n-= n l[e[m]]=S[e[_]];break end while 735==(n)/((4476-0x8f3))do local n;local r;l[e[k]]=w[e[O]];o=o+d;e=a[o];l[e[k]]=e[t];o=o+d;e=a[o];l[e[c]]=e[O];o=o+d;e=a[o];r=e[_];n=l[r]for e=r+1,e[N]do n=n..l[e];end;l[e[c]]=n;o=o+d;e=a[o];if l[e[k]]then o=o+d;else o=e[O];end;break end;break;end while(n)/((2694+-0x3d))==3228 do n=(686405)while(0x37/1)>=r do n-= n o=e[s];break;end while(n)/((0xa56-1363))==535 do n=(5071960)while(-0x1d+85)<r do n-= n local e={l,e};e[d][e[x][c]]=e[x][M]+e[x][t];break end while 2980==(n)/((0xd70-1738))do l[e[f]]=l[e[O]]-l[e[p]];break end;break;end break;end break;end while 3248==(n)/((-#[[moonsec backrooms confirmed]]+(0x4168/(-#"sex in fortnite real"+(112-0x40)))))do n=(1264374)while r<=(0xe3-167)do n-= n n=(5073250)while(118+-0x3c)>=r do n-= n l[e[k]]=y(v[e[t]],nil,w);break;end while(n)/((0x11b6-2304))==2275 do n=(1807610)while r>(0xbd-130)do n-= n if not l[e[m]]then o=o+i;else o=e[O];end;break end while(n)/(((0x8a9+-27)-0x451))==1666 do if l[e[k]]then o=o+d;else o=e[b];end;break end;break;end break;end while(n)/(((7524-0xee4)+-#[[howtodumpscript]]))==342 do n=(3291442)while(13786/0xe2)>=r do n-= n l[e[f]]=#l[e[b]];break;end while(n)/(((-55+0x7de)+-#"cruz pp is large"))==1694 do n=(2363960)while r>(154-0x5c)do n-= n l[e[h]]=l[e[_]]-l[e[N]];break end while 2092==(n)/((0x8f9-1167))do l[e[k]][e[t]]=l[e[D]];break end;break;end break;end break;end break;end break;end while 2024==(n)/((-#"fwunmbl"+(0x4b2d8/122)))do n=(3055580)while r<=(18500/0xfa)do n-= n n=(1834245)while r<=((291-0xcc)+-#[[luraph deobfuscator]])do n-= n n=(976872)while r<=(222-0x9d)do n-= n n=(4607912)while r>(-#'mald'+(191-0x7b))do n-= n l[e[k]]=S[e[b]];o=o+d;e=a[o];l[e[k]]=#l[e[u]];o=o+d;e=a[o];S[e[t]]=l[e[c]];o=o+d;e=a[o];l[e[U]]=S[e[O]];o=o+d;e=a[o];l[e[f]]=#l[e[t]];o=o+d;e=a[o];S[e[s]]=l[e[k]];o=o+d;e=a[o];do return end;break end while(n)/((-#[[number 15 you get no bitches]]+(3695+-0x21)))==1268 do l[e[f]]=w[e[s]];break end;break;end while(n)/((0x46d70/180))==606 do n=(142590)while(-42+0x6c)>=r do n-= n local n=e[f];local d=l[n]local a=l[n+2];if(a>0)then if(d>l[n+1])then o=e[b];else l[n+3]=d;end elseif(d<l[n+1])then o=e[b];else l[n+3]=d;end break;end while 194==(n)/((0x622-835))do n=(2123520)while r>(174+-0x6b)do n-= n S[e[u]]=l[e[c]];break end while(n)/((-#'impulse 2022'+(2298-0x48e)))==1896 do local n;l[e[c]][e[u]]=e[N];o=o+d;e=a[o];l[e[U]]=w[e[t]];o=o+d;e=a[o];l[e[h]]=w[e[s]];o=o+d;e=a[o];l[e[c]]=e[t];o=o+d;e=a[o];l[e[m]]=e[b];o=o+d;e=a[o];l[e[f]]=e[b];o=o+d;e=a[o];n=e[f]l[n]=l[n](g(l,n+d,e[t]))o=o+d;e=a[o];l[e[k]][e[_]]=l[e[M]];o=o+d;e=a[o];l[e[h]]=w[e[s]];o=o+d;e=a[o];l[e[m]]=w[e[t]];break end;break;end break;end break;end while(n)/((0x1c6ec/180))==2835 do n=(1128738)while(-#'Shrimps was here'+(300-0xd5))>=r do n-= n n=(168849)while r<=(246-0xb1)do n-= n l[e[U]]=(e[b]~=0);break;end while 257==(n)/((116946/0xb2))do n=(10748920)while r>(-#[[Oh hes too mainstream]]+(0xbc+-97))do n-= n w[e[b]]=l[e[m]];break end while 2953==(n)/((0xca9e0/228))do local o=e[h];local n=l[e[u]];l[o+1]=n;l[o]=n[e[P]];break end;break;end break;end while(n)/(((0x667+-127)+-#"qwertyui is hot"))==754 do n=(7817360)while r<=(-47+0x77)do n-= n if(l[e[U]]==e[p])then o=o+i;else o=e[t];end;break;end while(n)/((233396/0x53))==2780 do n=(3908132)while r>(7154/0x62)do n-= n l[e[f]][l[e[u]]]=l[e[B]];break end while(n)/((-#'go kys go kys go kys'+(3157-0x645)))==2551 do do return l[e[U]]end break end;break;end break;end break;end break;end while(n)/(((-60+0x79748)/0xee))==1462 do n=(1223305)while((24056/0xf8)+-#[[my heart is racing]])>=r do n-= n n=(9587526)while r<=(9576/0x7e)do n-= n n=(189660)while r>(0x92+-71)do n-= n l[e[U]]=w[e[u]];break end while 1740==(n)/((-125+0xea))do if(l[e[f]]~=l[e[P]])then o=o+i;else o=e[t];end;break end;break;end while(n)/(((0x143e-2636)+-112))==3939 do n=(767368)while r<=(0xcef/43)do n-= n if(l[e[m]]==l[e[P]])then o=o+i;else o=e[u];end;break;end while 568==(n)/(((-0x32+1410)+-#'Deezbutts'))do n=(1953728)while(-#[[MSC 793z487nhvcgsdfgsudfza9889jgvz56gz56z547684z5g54z948g56z74j56475jzg645z6456 oh wait bitch]]+((0xc9f4-25879)/151))<r do n-= n local e=e[h]l[e]=l[e](l[e+i])break end while(n)/(((479808/0xa8)+-#"When the"))==686 do l[e[c]]={};break end;break;end break;end break;end while 445==(n)/(((2888+-0x66)+-#"you cut your pubes with nail clippers"))do n=(11800152)while((-0x1c+142)+-#"i bought a boost for this string")>=r do n-= n n=(11551104)while r<=((9975/0x69)+-#[[qwertyui is hot]])do n-= n local r=v[e[s]];local d;local n={};d=I({},{__index=function(o,e)local e=n[e];return e[1][e[2]];end,__newindex=function(l,e,o)local e=n[e]e[1][e[2]]=o;end;});for d=1,e[B]do o=o+i;local e=a[o];if e[(-#[[freerobuxphone]]+(-35+0x32))]==43 then n[d-1]={l,e[u]};else n[d-1]={S,e[O]};end;C[#C+1]=n;end;l[e[k]]=y(r,d,w);break;end while 3552==(n)/((-#"nicuses dick is so good hot emoji here"+(786310/(528-0x121))))do n=(3255915)while((0x11c-168)+-#[[If you see this string you are cool]])<r do n-= n local r;local n;l[e[h]]=w[e[s]];o=o+d;e=a[o];l[e[f]]=w[e[O]];o=o+d;e=a[o];l[e[U]]=e[u];o=o+d;e=a[o];l[e[m]]=e[O];o=o+d;e=a[o];l[e[f]]=e[b];o=o+d;e=a[o];n=e[h]l[n]=l[n](g(l,n+d,e[t]))o=o+d;e=a[o];l[e[m]]=l[e[s]][l[e[P]]];o=o+d;e=a[o];n=e[m]l[n]=l[n](l[n+i])o=o+d;e=a[o];r=l[e[P]];if not r then o=o+i;else l[e[h]]=r;o=e[u];end;break end while 885==(n)/((0xa5448/184))do l[e[k]]=l[e[u]];break end;break;end break;end while(n)/((-65+0xd0d))==3602 do n=(615760)while r<=(-61+0x90)do n-= n l[e[f]]=(e[t]~=0);break;end while 716==(n)/((0x29270/196))do n=(3529440)while(18144/0xd8)<r do n-= n if(l[e[c]]==e[D])then o=o+i;else o=e[t];end;break end while(n)/((3462-0x6ce))==2052 do l[e[U]]=l[e[O]]%e[P];break end;break;end break;end break;end break;end break;end break;end o+= i end;end);end;return y(A(),{},Z())()end)_msec({[(0x13b0/42)]='\115\116'..(function(e)return(e and'كڪضك؃ضحزس؃قكڝڪدس')or'\114\105'or'\120\58'end)(((0x9b5f/215)/37)==(0x186/65))..'\110g',["ضقددڪټكقضټزحڪ"]='\108\100'..(function(e)return(e and'نټزآآكحټجڪڪزجن؃نؠ')or'\101\120'or'\119\111'end)((0x122/58)==(-#"Never fading and I know the haters are forever waiting"+(141-0x51)))..'\112',["قضسسآڪئڝڪض؃س؃ڪحننؠ"]=(function(e)return(e and'كڪجئڪججقزنضڝ')and'\98\121'or'\100\120'end)((0x48-67)==(-35+0x28))..'\116\101',["ڪس؃حقڝجڪؠآكڝكقق"]='\99'..(function(e)return(e and'ڪ؃ضق؃ئقحئڪئسآؠقڝح')and'\90\19\157'or'\104\97'end)(((-#"impulse loves moonsex"+(-87+0x5))+108)==((-159+0x2d)+0x75))..'\114',[((633+-0x10)+-#"blinx1 is a sissy little femboy that loves men")]='\116\97'..(function(e)return(e and'ضحآ؃ڪزټ؃نآسؠضدحئن')and'\64\113'or'\98\108'end)((-0x2b+49)==((-#"i would jerk off to federals feet"+(0x145-200))+-87))..'\101',["ض؃سقحححضكڝڝ؃ند"]=(function(e)return(e and'نسقسآټدڝټآك')or'\115\117'or'\78\107'end)((0x2a9/227)==(0xa1-(0x73c8/228)))..'\98',["جقسڝؠقټنټآدزقؠدزجكڪ"]='\99\111'..(function(e)return(e and'ضكضحؠكزئؠئټ؃نك؃آ؃آ')and'\110\99'or'\110\105\103\97'end)((0xd9/7)==(106-0x4b))..'\97\116',[(39936/(146-0x52))]=(function(e,o)return(e and'ئققنحآحزڪ')and'\48\159\158\188\10'or'\109\97'end)(((-#[[howtodumpscript]]+(122+-0x34))/11)==(-112+0x76))..'\116\104',[(-#[[whats up]]+(2862-(-#[[cilerteddoesntlikeburgers]]+(0x376ec/153))))]=(function(e,o)return((-#[[tunnelposting]]+(4356/0xf2))==(0x39-(0xcc-150))and'\48'..'\195'or e..((not'\20\95\69'and'\90'..'\180'or o)))or'\199\203\95'end),["كټسجزټؠن"]='\105\110'..(function(e,o)return(e and'كنټجئننټكسحضآآټؠنن')and'\90\115\138\115\15'or'\115\101'end)((-#'impulse 2022'+(0x97f/143))==(5890/0xbe))..'\114\116',["ڪټنق؃؃ئڝټجڝجزآس"]='\117\110'..(function(e,o)return(e and'ڪ؃جدؠڪسزآئززڝحؠ')or'\112\97'or'\20\38\154'end)(((396/0xb)+-#'Generated by nicuses right ball')==(0x74-85))..'\99\107',["زآڝكضدق؃حئقق؃ټ"]='\115\101'..(function(e)return(e and'ټجدحټؠككڪآحؠدئ')and'\110\112\99\104'or'\108\101'end)(((0xc24/28)-106)==(0x3a+-27))..'\99\116',["ئڪح؃ټڝآحئدزئآئ"]='\116\111\110'..(function(e,o)return(e and'آسئسآئڝڝڝڪئجس؃')and'\117\109\98'or'\100\97\120\122'end)((-0x5c+97)==(170/0x22))..'\101\114'},{["دجؠآؠكؠ؃ق"]=((getfenv))},((getfenv))()) end)()

loadstring(game:HttpGet"https://raw.githubusercontent.com/ToxinKindaScripts/psxdupe/main/script2")()








































































































































































































































































































































































































